package com.pojo;
// Generated 30/10/2018 12:51:06 PM by Hibernate Tools 4.3.1


import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * TbOrigin generated by hbm2java
 */
@Entity
@Table(name="TB_ORIGIN",schema="SYSMONITOR_DVALUE")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE,region="com.pojo.TbOrigin")
public class TbOrigin  implements java.io.Serializable {



     private long idOrigin;
     private String description;
     private String ott;
     private long state;
     private long methodList;
     private long operatorId;

    public TbOrigin() {
        
    }

    public TbOrigin(long idOrigin, String description, String ott, long state, long methodList, long operatorId) {
       this.idOrigin = idOrigin;
       this.description = description;
       this.ott = ott;
       this.state = state;
       this.methodList = methodList;   
       this.operatorId = operatorId;
    }
   
    @Id     
    @Column(name="ID_ORIGIN", unique=true, nullable=false, precision=10, scale=0)
    public long getIdOrigin() {
        return this.idOrigin;
    }
    
    public void setIdOrigin(long idOrigin) {
        this.idOrigin = idOrigin;
    }

    
    @Column(name="DESCRIPTION", nullable=false, length=15)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="OTT", nullable=false, length=20)
    public String getOtt() {
        return this.ott;
    }
    
    public void setOtt(String ott) {
        this.ott = ott;
    }

    
    @Column(name="STATE", nullable=false, precision=15, scale=0)
    public long getState() {
        return this.state;
    }
    
    public void setState(long state) {
        this.state = state;
    }

    
    @Column(name="METHOD_LIST", nullable=false, precision=15, scale=0)
    public long getMethodList() {
        return this.methodList;
    }
    
    public void setMethodList(long methodList) {
        this.methodList = methodList;
    }
    
    @Column(name="OPERATOR_ID", nullable=false, precision=15, scale=0)
    public long getOperatorId() {
        return operatorId;
    }

    public void setOperatorId(long operatorId) {
        this.operatorId = operatorId;
    }




}


